// Convert 2-letter country code to flag emoji
export const toFlag = (cc: string) =>
  cc.toUpperCase().replace(/./g, (c) => String.fromCodePoint(0x1f1e6 + c.charCodeAt(0) - 65));

export const countryCodes = [
  { code: "+1", cc: "US" }, { code: "+44", cc: "GB" }, { code: "+93", cc: "AF" },
  { code: "+355", cc: "AL" }, { code: "+213", cc: "DZ" }, { code: "+376", cc: "AD" },
  { code: "+244", cc: "AO" }, { code: "+54", cc: "AR" }, { code: "+374", cc: "AM" },
  { code: "+61", cc: "AU" }, { code: "+43", cc: "AT" }, { code: "+994", cc: "AZ" },
  { code: "+973", cc: "BH" }, { code: "+880", cc: "BD" }, { code: "+375", cc: "BY" },
  { code: "+32", cc: "BE" }, { code: "+501", cc: "BZ" }, { code: "+229", cc: "BJ" },
  { code: "+975", cc: "BT" }, { code: "+591", cc: "BO" }, { code: "+387", cc: "BA" },
  { code: "+267", cc: "BW" }, { code: "+55", cc: "BR" }, { code: "+673", cc: "BN" },
  { code: "+359", cc: "BG" }, { code: "+226", cc: "BF" }, { code: "+257", cc: "BI" },
  { code: "+855", cc: "KH" }, { code: "+237", cc: "CM" }, { code: "+1", cc: "CA" },
  { code: "+236", cc: "CF" }, { code: "+235", cc: "TD" }, { code: "+56", cc: "CL" },
  { code: "+86", cc: "CN" }, { code: "+57", cc: "CO" }, { code: "+269", cc: "KM" },
  { code: "+243", cc: "CD" }, { code: "+242", cc: "CG" }, { code: "+506", cc: "CR" },
  { code: "+225", cc: "CI" }, { code: "+385", cc: "HR" }, { code: "+53", cc: "CU" },
  { code: "+357", cc: "CY" }, { code: "+420", cc: "CZ" }, { code: "+45", cc: "DK" },
  { code: "+253", cc: "DJ" }, { code: "+593", cc: "EC" }, { code: "+20", cc: "EG" },
  { code: "+503", cc: "SV" }, { code: "+240", cc: "GQ" }, { code: "+291", cc: "ER" },
  { code: "+372", cc: "EE" }, { code: "+268", cc: "SZ" }, { code: "+251", cc: "ET" },
  { code: "+679", cc: "FJ" }, { code: "+358", cc: "FI" }, { code: "+33", cc: "FR" },
  { code: "+241", cc: "GA" }, { code: "+220", cc: "GM" }, { code: "+995", cc: "GE" },
  { code: "+49", cc: "DE" }, { code: "+233", cc: "GH" }, { code: "+30", cc: "GR" },
  { code: "+502", cc: "GT" }, { code: "+224", cc: "GN" }, { code: "+592", cc: "GY" },
  { code: "+509", cc: "HT" }, { code: "+504", cc: "HN" }, { code: "+852", cc: "HK" },
  { code: "+36", cc: "HU" }, { code: "+354", cc: "IS" }, { code: "+91", cc: "IN" },
  { code: "+62", cc: "ID" }, { code: "+98", cc: "IR" }, { code: "+964", cc: "IQ" },
  { code: "+353", cc: "IE" }, { code: "+972", cc: "IL" }, { code: "+39", cc: "IT" },
  { code: "+876", cc: "JM" }, { code: "+81", cc: "JP" }, { code: "+962", cc: "JO" },
  { code: "+7", cc: "KZ" }, { code: "+254", cc: "KE" }, { code: "+965", cc: "KW" },
  { code: "+996", cc: "KG" }, { code: "+856", cc: "LA" }, { code: "+371", cc: "LV" },
  { code: "+961", cc: "LB" }, { code: "+266", cc: "LS" }, { code: "+231", cc: "LR" },
  { code: "+218", cc: "LY" }, { code: "+370", cc: "LT" }, { code: "+352", cc: "LU" },
  { code: "+261", cc: "MG" }, { code: "+265", cc: "MW" }, { code: "+60", cc: "MY" },
  { code: "+960", cc: "MV" }, { code: "+223", cc: "ML" }, { code: "+356", cc: "MT" },
  { code: "+222", cc: "MR" }, { code: "+230", cc: "MU" }, { code: "+52", cc: "MX" },
  { code: "+373", cc: "MD" }, { code: "+976", cc: "MN" }, { code: "+382", cc: "ME" },
  { code: "+212", cc: "MA" }, { code: "+258", cc: "MZ" }, { code: "+95", cc: "MM" },
  { code: "+264", cc: "NA" }, { code: "+977", cc: "NP" }, { code: "+31", cc: "NL" },
  { code: "+64", cc: "NZ" }, { code: "+505", cc: "NI" }, { code: "+227", cc: "NE" },
  { code: "+234", cc: "NG" }, { code: "+850", cc: "KP" }, { code: "+389", cc: "MK" },
  { code: "+47", cc: "NO" }, { code: "+968", cc: "OM" }, { code: "+92", cc: "PK" },
  { code: "+507", cc: "PA" }, { code: "+675", cc: "PG" }, { code: "+595", cc: "PY" },
  { code: "+51", cc: "PE" }, { code: "+63", cc: "PH" }, { code: "+48", cc: "PL" },
  { code: "+351", cc: "PT" }, { code: "+974", cc: "QA" }, { code: "+40", cc: "RO" },
  { code: "+7", cc: "RU" }, { code: "+250", cc: "RW" }, { code: "+966", cc: "SA" },
  { code: "+221", cc: "SN" }, { code: "+381", cc: "RS" }, { code: "+232", cc: "SL" },
  { code: "+65", cc: "SG" }, { code: "+421", cc: "SK" }, { code: "+386", cc: "SI" },
  { code: "+252", cc: "SO" }, { code: "+27", cc: "ZA" }, { code: "+82", cc: "KR" },
  { code: "+211", cc: "SS" }, { code: "+34", cc: "ES" }, { code: "+94", cc: "LK" },
  { code: "+249", cc: "SD" }, { code: "+597", cc: "SR" }, { code: "+46", cc: "SE" },
  { code: "+41", cc: "CH" }, { code: "+963", cc: "SY" }, { code: "+886", cc: "TW" },
  { code: "+992", cc: "TJ" }, { code: "+255", cc: "TZ" }, { code: "+66", cc: "TH" },
  { code: "+228", cc: "TG" }, { code: "+216", cc: "TN" }, { code: "+90", cc: "TR" },
  { code: "+993", cc: "TM" }, { code: "+256", cc: "UG" }, { code: "+380", cc: "UA" },
  { code: "+971", cc: "AE" }, { code: "+598", cc: "UY" }, { code: "+998", cc: "UZ" },
  { code: "+58", cc: "VE" }, { code: "+84", cc: "VN" }, { code: "+967", cc: "YE" },
  { code: "+260", cc: "ZM" }, { code: "+263", cc: "ZW" },
];

export const DEFAULT_COUNTRY_VALUE = "US|+1";

export const getDialCode = (value: string) => value.split("|")[1] || "+1";
