project_id = "fuashqzjafotjinulyyk"

[functions.pesapal-payment]
verify_jwt = false

[functions.public-forms]
verify_jwt = false

[functions.admin-api]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.paypal-payment]
verify_jwt = false
