ALTER TABLE public.donations
  ADD COLUMN IF NOT EXISTS currency TEXT NOT NULL DEFAULT 'USD',
  ADD COLUMN IF NOT EXISTS charged_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS amount_ugx NUMERIC,
  ADD COLUMN IF NOT EXISTS ugx_rate NUMERIC;